Add landshare to JSON list of instances
defactor-com/documentation pull request #121
Opened 2024-07-28 01:36 UTC by xavier506

### Add landshare to JSON list of instances

2024-07-29 14:48 UTC, AngeloCG97 approved these changes

2024-07-29 14:58 UTC, leisterfrancisco requested changes

2024-07-29 14:58 UTC, leisterfrancisco commented on static/defactor-pools.json
> +        "contract": "0x7D5c1468D8bE9f0F4FaD26F2Cb7e6b2ed9042577",
```text
FACTR deployed on: 0x7D5c1468D8bE9f0F4FaD26F2Cb7e6b2ed9042577
```

https://sepolia.etherscan.io/address/0x7D5c1468D8bE9f0F4FaD26F2Cb7e6b2ed9042577

That address belongs to `FACTR`, it's wrong.

2024-07-29 14:58 UTC, leisterfrancisco commented on static/defactor-pools.json
> +        "id": "Base",
It is `sepolia`, not `base`.

Base -> mainnet
Sepolia -> testnet

2024-08-01 12:54 UTC, leisterfrancisco approved these changes

2024-08-01 12:54 UTC, merged